# Generated by Django 5.1.2 on 2024-11-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(max_length=50)),
                ('paymentAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentDate', models.DateField()),
                ('paymentStatus', models.CharField(max_length=50)),
            ],
        ),
    ]
