# Generated by Django 5.1.2 on 2024-11-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingStatus', models.CharField(max_length=255)),
                ('numberOfGuests', models.IntegerField(default=0)),
                ('checkInDate', models.DateTimeField(blank=True, null=True)),
                ('checkOutDate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
