# Generated by Django 5.1.3 on 2024-11-24 15:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('customer_entity', '0001_initial'),
        ('payment', '0001_initial'),
        ('room', '0002_alter_room_roomnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingStatus',
            new_name='booking_status',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='numberOfGuests',
            new_name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkInDate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkOutDate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(default=datetime.date(2024, 11, 24)),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customer_entity.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='room.room'),
        ),
    ]
