# Generated by Django 5.1.3 on 2024-11-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_entity', '0003_rename_location_hotel_hotelname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
