# Generated by Django 5.1.2 on 2024-11-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotelID', models.AutoField(primary_key=True, serialize=False)),
                ('hotelName', models.CharField(max_length=255)),
            ],
        ),
    ]
