# Generated by Django 5.1.2 on 2024-11-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_entity', '0001_initial'),
        ('hotel', '0002_hotel_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_entity.adminentity'),
        ),
    ]
