# Generated by Django 5.1.3 on 2024-11-24 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_entity', '0001_initial'),
        ('hotel', '0003_alter_hotel_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_entity.adminentity'),
        ),
    ]
