# Generated by Django 5.1.3 on 2024-11-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
