# Generated by Django 5.1.3 on 2024-11-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_entity', '0001_initial'),
        ('hotel', '0005_hotel_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='is_featured',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_entity.adminentity'),
        ),
    ]
