# Generated by Django 5.1.3 on 2024-11-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
